// Code generated by options-gen. DO NOT EDIT.
package database

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	address string,
	username string,
	password string,
	database string,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)
	o.retry = true

	o.retryAttempts = 1

	o.maxOpenConns = 5

	o.maxIdleConns = 5

	o.address = address

	o.username = username

	o.password = password

	o.database = database

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithRetry(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.retry = opt

	}
}

func WithRetryAttempts(opt uint) OptOptionsSetter {
	return func(o *Options) {
		o.retryAttempts = opt

	}
}

func WithLogger(opt logger) OptOptionsSetter {
	return func(o *Options) {
		o.logger = opt

	}
}

// TODO: use in pool later
func WithMaxOpenConns(opt int) OptOptionsSetter {
	return func(o *Options) {
		o.maxOpenConns = opt

	}
}

func WithMaxIdleConns(opt int) OptOptionsSetter {
	return func(o *Options) {
		o.maxIdleConns = opt

	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("address", _validate_Options_address(o)))
	errs.Add(errors461e464ebed9.NewValidationError("username", _validate_Options_username(o)))
	errs.Add(errors461e464ebed9.NewValidationError("password", _validate_Options_password(o)))
	errs.Add(errors461e464ebed9.NewValidationError("database", _validate_Options_database(o)))
	errs.Add(errors461e464ebed9.NewValidationError("retryAttempts", _validate_Options_retryAttempts(o)))
	errs.Add(errors461e464ebed9.NewValidationError("maxOpenConns", _validate_Options_maxOpenConns(o)))
	errs.Add(errors461e464ebed9.NewValidationError("maxIdleConns", _validate_Options_maxIdleConns(o)))
	return errs.AsError()
}

func _validate_Options_address(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.address, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `address` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_username(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.username, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `username` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_password(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.password, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `password` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_database(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.database, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `database` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_retryAttempts(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.retryAttempts, "min=1,max=10"); err != nil {
		return fmt461e464ebed9.Errorf("field `retryAttempts` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_maxOpenConns(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.maxOpenConns, "max=20"); err != nil {
		return fmt461e464ebed9.Errorf("field `maxOpenConns` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_maxIdleConns(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.maxIdleConns, "max=20"); err != nil {
		return fmt461e464ebed9.Errorf("field `maxIdleConns` did not pass the test: %w", err)
	}
	return nil
}
