// Code generated by options-gen v0.55.3. DO NOT EDIT.

package grpcx

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"google.golang.org/grpc"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	addr string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.maxConnIdle, _ = time.ParseDuration("5m")
	o.time, _ = time.ParseDuration("2h")
	o.timeout, _ = time.ParseDuration("20s")

	o.addr = addr

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithServices(opt ...Service) OptOptionsSetter {
	return func(o *Options) { o.services = append(o.services, opt...) }
}

func WithLogger(opt logger) OptOptionsSetter {
	return func(o *Options) { o.logger = opt }
}

func WithGrpcOptions(opt ...grpc.ServerOption) OptOptionsSetter {
	return func(o *Options) { o.grpcOptions = append(o.grpcOptions, opt...) }
}

func WithMaxConnIdle(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.maxConnIdle = opt }
}

func WithTime(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.time = opt }
}

func WithTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.timeout = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("services", _validate_Options_services(o)))
	return errs.AsError()
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_services(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.services, "required,min=1"); err != nil {
		return fmt461e464ebed9.Errorf("field `services` did not pass the test: %w", err)
	}
	return nil
}
